# Dicionário de mecanismos IPCS
declare -A func_dict
func_dict["pipe"]="pipe"
func_dict["pipe2"]="pipe"

func_dict["mkfifo"]="fifo"

func_dict["socket"]="socket"
func_dict["bind"]="socket"
func_dict["listen"]="socket"
func_dict["accept"]="socket"
func_dict["connect"]="socket"
func_dict["send"]="socket"
func_dict["recv"]="socket"
func_dict["sendto"]="socket"
func_dict["recvfrom"]="socket"
func_dict["socketpair"]="socket"

func_dict["posix_openpt"]="pseudo_terminal"
func_dict["grantpt"]="pseudo_terminal"
func_dict["unlockpt"]="pseudo_terminal"
func_dict["ptsname"]="pseudo_terminal"

func_dict["msgget"]="sysv_message_queues"
func_dict["msgsnd"]="sysv_message_queues"
func_dict["msgrcv"]="sysv_message_queues"
func_dict["msgctl"]="sysv_message_queues"

func_dict["mq_open"]="posix_message_queues"
func_dict["mq_send"]="posix_message_queues"
func_dict["mq_receive"]="posix_message_queues"
func_dict["mq_close"]="posix_message_queues"
func_dict["mq_unlink"]="posix_message_queues"

func_dict["process_vm_readv"]="cross_memory_attach"
func_dict["process_vm_writev"]="cross_memory_attach"

func_dict["shmget"]="sysv_shared_memory"
func_dict["shmat"]="sysv_shared_memory"
func_dict["shmdt"]="sysv_shared_memory"
func_dict["shmctl"]="sysv_shared_memory"

func_dict["shm_open"]="posix_shared_memory"
func_dict["shm_unlink"]="posix_shared_memory"

func_dict["mmap"]="mmap"
func_dict["munmap"]="anonymous_memory_mapping"
func_dict["msync"]="anonymous_memory_mapping"

func_dict["semget"]="sysv_semaphores"
func_dict["semop"]="sysv_semaphores"
func_dict["semctl"]="sysv_semaphores"

func_dict["sem_init"]="posix_semaphores"
func_dict["sem_destroy"]="posix_semaphores"
func_dict["sem_wait"]="posix_semaphores"
func_dict["sem_trywait"]="posix_semaphores"
func_dict["sem_post"]="posix_semaphores"
func_dict["sem_getvalue"]="posix_semaphores"
func_dict["sem_timedwait"]="posix_semaphores"

func_dict["eventfd"]="eventfd"
func_dict["eventfd2"]="eventfd"
func_dict["eventfd_read"]="eventfd"
func_dict["eventfd_write"]="eventfd"
func_dict["flock"]="file_and_record_locks"
func_dict["fcntl"]="file_and_record_locks"
func_dict["lockf"]="file_and_record_locks"

func_dict["pthread_mutex_init"]="mutexes"
func_dict["pthread_mutex_destroy"]="mutexes"
func_dict["pthread_mutex_lock"]="mutexes"
func_dict["pthread_mutex_trylock"]="mutexes"
func_dict["pthread_mutex_unlock"]="mutexes"
func_dict["pthread_mutex_timedlock"]="mutexes"
func_dict["pthread_mutexattr_init"]="mutexes"
func_dict["pthread_mutexattr_destroy"]="mutexes"
func_dict["pthread_mutexattr_settype"]="mutexes"
func_dict["pthread_mutexattr_gettype"]="mutexes"

func_dict["pthread_cond_init"]="condition_variables"
func_dict["pthread_cond_destroy"]="condition_variables"
func_dict["pthread_cond_wait"]="condition_variables"
func_dict["pthread_cond_timedwait"]="condition_variables"
func_dict["pthread_cond_signal"]="condition_variables"
func_dict["pthread_cond_broadcast"]="condition_variables"
func_dict["pthread_condattr_init"]="condition_variables"
func_dict["pthread_condattr_destroy"]="condition_variables"
func_dict["pthread_condattr_setclock"]="condition_variables"
func_dict["pthread_condattr_getclock"]="condition_variables"

func_dict["pthread_barrier_init"]="barriers"
func_dict["pthread_barrier_destroy"]="barriers"
func_dict["pthread_barrier_wait"]="barriers"
func_dict["pthread_barrierattr_init"]="barriers"
func_dict["pthread_barrierattr_destroy"]="barriers"
func_dict["pthread_barrierattr_setpshared"]="barriers"
func_dict["pthread_barrierattr_getpshared"]="barriers"

func_dict["pthread_rwlock_init"]="read_write_locks"
func_dict["pthread_rwlock_destroy"]="read_write_locks"
func_dict["pthread_rwlock_rdlock"]="read_write_locks"
func_dict["pthread_rwlock_tryrdlock"]="read_write_locks"
func_dict["pthread_rwlock_wrlock"]="read_write_locks"
func_dict["pthread_rwlock_trywrlock"]="read_write_locks"
func_dict["pthread_rwlock_unlock"]="read_write_locks"
func_dict["pthread_rwlock_timedrdlock"]="read_write_locks"
func_dict["pthread_rwlock_timedwrlock"]="read_write_locks"
func_dict["pthread_rwlockattr_init"]="read_write_locks"
func_dict["pthread_rwlockattr_destroy"]="read_write_locks"
func_dict["pthread_rwlockattr_setpshared"]="read_write_locks"
func_dict["pthread_rwlockattr_getpshared"]="read_write_locks"
