# Dicionário de mecanismos IPCS
declare -A func_dict
func_dict["pipe"]="Pipes"
func_dict["pipe2"]="Pipes"

func_dict["mkfifo"]="FIFOs"

func_dict["socket"]="Sockets"
func_dict["bind"]="Sockets"
func_dict["listen"]="Sockets"
func_dict["accept"]="Sockets"
func_dict["connect"]="Sockets"
func_dict["send"]="Sockets"
func_dict["recv"]="Sockets"
func_dict["sendto"]="Sockets"
func_dict["recvfrom"]="Sockets"
func_dict["socketpair"]="Sockets"

func_dict["posix_openpt"]="Pseudo-Terminals"
func_dict["grantpt"]="Pseudo-Terminals"
func_dict["unlockpt"]="Pseudo-Terminals"
func_dict["ptsname"]="Pseudo-Terminals"

func_dict["msgget"]="SysV Message Queues"
func_dict["msgsnd"]="SysV Message Queues"
func_dict["msgrcv"]="SysV Message Queues"
func_dict["msgctl"]="SysV Message Queues"

func_dict["mq_open"]="POSIX Message Queues"
func_dict["mq_send"]="POSIX Message Queues"
func_dict["mq_receive"]="POSIX Message Queues"
func_dict["mq_close"]="POSIX Message Queues"
func_dict["mq_unlink"]="POSIX Message Queues"

func_dict["process_vm_readv"]="Cross-Memory Attach"
func_dict["process_vm_writev"]="Cross-Memory Attach"

func_dict["shmget"]="SysV Shared Memory"
func_dict["shmat"]="SysV Shared Memory"
func_dict["shmdt"]="SysV Shared Memory"
func_dict["shmctl"]="SysV Shared Memory"

func_dict["shm_open"]="POSIX Shared Memory"
func_dict["shm_unlink"]="POSIX Shared Memory"

func_dict["mmap"]="Memory Mapping"

func_dict["munmap"]="Anonymous Memory Mapping"
func_dict["msync"]="Anonymous Memory Mapping"

func_dict["semget"]="SysV Semaphores"
func_dict["semop"]="SysV Semaphores"
func_dict["semctl"]="SysV Semaphores"

func_dict["sem_init"]="POSIX Semaphores"
func_dict["sem_destroy"]="POSIX Semaphores"
func_dict["sem_wait"]="POSIX Semaphores"
func_dict["sem_trywait"]="POSIX Semaphores"
func_dict["sem_post"]="POSIX Semaphores"
func_dict["sem_getvalue"]="POSIX Semaphores"
func_dict["sem_timedwait"]="POSIX Semaphores"

func_dict["eventfd"]="EventFD"
func_dict["eventfd2"]="EventFD"
func_dict["eventfd_read"]="EventFD"
func_dict["eventfd_write"]="EventFD"
func_dict["flock"]="File and Record Locks"
func_dict["fcntl"]="File and Record Locks"
func_dict["lockf"]="File and Record Locks"

func_dict["pthread_mutex_init"]="Mutexes"
func_dict["pthread_mutex_destroy"]="Mutexes"
func_dict["pthread_mutex_lock"]="Mutexes"
func_dict["pthread_mutex_trylock"]="Mutexes"
func_dict["pthread_mutex_unlock"]="Mutexes"
func_dict["pthread_mutex_timedlock"]="Mutexes"
func_dict["pthread_mutexattr_init"]="Mutexes"
func_dict["pthread_mutexattr_destroy"]="Mutexes"
func_dict["pthread_mutexattr_settype"]="Mutexes"
func_dict["pthread_mutexattr_gettype"]="Mutexes"

func_dict["pthread_cond_init"]="Condition Variables"
func_dict["pthread_cond_destroy"]="Condition Variables"
func_dict["pthread_cond_wait"]="Condition Variables"
func_dict["pthread_cond_timedwait"]="Condition Variables"
func_dict["pthread_cond_signal"]="Condition Variables"
func_dict["pthread_cond_broadcast"]="Condition Variables"
func_dict["pthread_condattr_init"]="Condition Variables"
func_dict["pthread_condattr_destroy"]="Condition Variables"
func_dict["pthread_condattr_setclock"]="Condition Variables"
func_dict["pthread_condattr_getclock"]="Condition Variables"

func_dict["pthread_barrier_init"]="Barriers"
func_dict["pthread_barrier_destroy"]="Barriers"
func_dict["pthread_barrier_wait"]="Barriers"
func_dict["pthread_barrierattr_init"]="Barriers"
func_dict["pthread_barrierattr_destroy"]="Barriers"
func_dict["pthread_barrierattr_setpshared"]="Barriers"
func_dict["pthread_barrierattr_getpshared"]="Barriers"

func_dict["pthread_rwlock_init"]="Read-Write Locks"
func_dict["pthread_rwlock_destroy"]="Read-Write Locks"
func_dict["pthread_rwlock_rdlock"]="Read-Write Locks"
func_dict["pthread_rwlock_tryrdlock"]="Read-Write Locks"
func_dict["pthread_rwlock_wrlock"]="Read-Write Locks"
func_dict["pthread_rwlock_trywrlock"]="Read-Write Locks"
func_dict["pthread_rwlock_unlock"]="Read-Write Locks"
func_dict["pthread_rwlock_timedrdlock"]="Read-Write Locks"
func_dict["pthread_rwlock_timedwrlock"]="Read-Write Locks"
func_dict["pthread_rwlockattr_init"]="Read-Write Locks"
func_dict["pthread_rwlockattr_destroy"]="Read-Write Locks"
func_dict["pthread_rwlockattr_setpshared"]="Read-Write Locks"
func_dict["pthread_rwlockattr_getpshared"]="Read-Write Locks"
